### PR TITLE
FindBiomimics script

### PR DESCRIPTION
**Pull request by sbliven**
Initial version of a script to identify biomimics, plus some assorted improvements

### CODE REVIEW

**Comment by josemduarte** [comment]
Great stuff! I'll try the FindBiomimics script as soon as I can!

**Comment by sbliven** [comment]
I was originally using ContactSets but they ended up not working for asymmetrical cases, so I had to create the MultipleInterfaceComparator instead. It should be fine to revert, but I'll try to keep in the comments I added.

**Comment by sbliven** [comment]
Fixed in 52ce684

**Comment by josemduarte** [comment]
Thanks! Yes indeed all the new comments are great

**Pull request merged**
